#train_file: 'data/comQA/train_rand_split.jsonl'
#val_file: 'data/comQA/dev_rand_split.jsonl'                
#test_file: 'data/comQA/test_rand_split_no_answers.jsonl'

train_file: 'data/winogrande/train_l.jsonl'
val_file: 'data/winogrande/dev.jsonl'                
test_file: 'data/winogrande/dev.jsonl'

image_root: '/mnt/blobfuse/data/'

image_res: 384
batch_size_train: 32 
batch_size_test: 32

alpha: 0.4
distill: True
warm_up: False
image: False

bert_config: 'configs/config_bert.json'
model_name: 'bert-base-uncased'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 30, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}
#optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
#schedular: {sched: cosine, lr: 1e-4, epochs: 30, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 20, cooldown_epochs: 0}







